include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - dependencies/**
    - integration_test/**
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/**/*.gen.dart
    - packages/**
    - test/**
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
