name: Release
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      version:
        description: "Tag to create (e.g. v2.10.0). Must include 'v' and must match pubspec"
        required: true
        default: "v1.0.0-alpha.0"
        type: string
      env:
        type: choice
        description: "Which environment are you using?"
        required: true
        default: "development"
        options:
          - development
          - staging
          - production
      versionSuffix:
        description: 'Whether to add version suffix?'
        default: true
        required: true
        type: boolean
      mode:
        type: choice
        description: "Which mode are you using? (iOS only)"
        required: true
        default: "debug"
        options:
          - debug
          - release

# Declare default permissions as read only.
permissions: read-all

jobs:
  draft-release:
    name: Draft Github release
    runs-on: ubuntu-latest
    needs:
      - apk-build
      - aab-build
      - ios-build
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: build/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: build/

      - name: Push APK to Releases
        if: github.event.inputs.versionSuffix == 'true'
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.inputs.version }}+${{ github.event.inputs.env }}
          artifacts: "./**/*.apk,./**/*.aab,./**/*.ipa"
          tag: ${{ github.event.inputs.version }}+${{ github.event.inputs.env }}
          token: ${{ secrets.CYF_BOT_TOKEN }}
          prerelease: ${{ github.event.inputs.env != 'production' }}

      - name: Push APK to Releases
        if: github.event.inputs.versionSuffix != 'true'
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.inputs.version }}
          artifacts: "./**/*.apk,./**/*.aab,./**/*.ipa"
          tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.CYF_BOT_TOKEN }}
          prerelease: ${{ github.event.inputs.env != 'production' }}

  apk-build:
    name: Create apk build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17.x"
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.2'

#      - name: Setup NDK
#        uses: nttld/setup-ndk@v1
#        with:
#          ndk-version: 'r21e'
#          add-to-path: true
#        env:
#          ANDROID_NDK_HOME: '/usr/local/lib/android/sdk/ndk'

      - name: Configure .env for development
        if: github.event.inputs.env == 'development'
        run: |
          echo "API_PREFIX=$API_PREFIX" >> .env
          echo "SIGN_KEY=$SIGN_KEY" >> .env
          echo "CRYPTO_AES_KEY=$CRYPTO_AES_KEY" >> .env
          echo "CRYPTO_AES_IV=$CRYPTO_AES_IV" >> .env
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
        env:
          API_PREFIX: ${{ secrets.DEV_API_PREFIX }}
          SIGN_KEY: ${{ secrets.DEV_SIGN_KEY }}
          CRYPTO_AES_KEY: ${{ secrets.DEV_CRYPTO_AES_KEY }}
          CRYPTO_AES_IV: ${{ secrets.DEV_CRYPTO_AES_IV }}
          SENTRY_DSN: ${{ secrets.DEV_SENTRY_DSN }}

      - name: Configure .env for staging
        if: github.event.inputs.env == 'staging'
        run: |
          echo "API_PREFIX=$API_PREFIX" >> .env
          echo "SIGN_KEY=$SIGN_KEY" >> .env
          echo "CRYPTO_AES_KEY=$CRYPTO_AES_KEY" >> .env
          echo "CRYPTO_AES_IV=$CRYPTO_AES_IV" >> .env
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
        env:
          API_PREFIX: ${{ secrets.STG_API_PREFIX }}
          SIGN_KEY: ${{ secrets.STG_SIGN_KEY }}
          CRYPTO_AES_KEY: ${{ secrets.STG_CRYPTO_AES_KEY }}
          CRYPTO_AES_IV: ${{ secrets.STG_CRYPTO_AES_IV }}
          SENTRY_DSN: ${{ secrets.STG_SENTRY_DSN }}

      - name: Configure .env for production
        if: github.event.inputs.env == 'production'
        run: |
          echo "API_PREFIX=$API_PREFIX" >> .env
          echo "SIGN_KEY=$SIGN_KEY" >> .env
          echo "CRYPTO_AES_KEY=$CRYPTO_AES_KEY" >> .env
          echo "CRYPTO_AES_IV=$CRYPTO_AES_IV" >> .env
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
        env:
          API_PREFIX: ${{ secrets.PROD_API_PREFIX }}
          SIGN_KEY: ${{ secrets.PROD_SIGN_KEY }}
          CRYPTO_AES_KEY: ${{ secrets.PROD_CRYPTO_AES_KEY }}
          CRYPTO_AES_IV: ${{ secrets.PROD_CRYPTO_AES_IV }}
          SENTRY_DSN: ${{ secrets.PROD_SENTRY_DSN }}

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Install Deps
        run: flutter pub get

      - name: Configure Keystore for Android
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      # Build the application.
      - if: github.event.inputs.versionSuffix == 'true'
        run: bash build-android.sh && flutter build apk --release --split-per-abi --no-tree-shake-icons

      - if: github.event.inputs.versionSuffix != 'true'
        run: flutter build apk --release --split-per-abi --no-tree-shake-icons

      # Package the build.
      - name: Copy build for Android
        run: cp *.apk $GITHUB_WORKSPACE/
        working-directory: build/app/outputs/flutter-apk

      - uses: actions/upload-artifact@v3
        with:
          name: apk-artifact
          path: ./*.apk

  aab-build:
    name: Create appbundle build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17.x"
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.2'

      #      - name: Setup NDK
      #        uses: nttld/setup-ndk@v1
      #        with:
      #          ndk-version: 'r21e'
      #          add-to-path: true
      #        env:
      #          ANDROID_NDK_HOME: '/usr/local/lib/android/sdk/ndk'

      - name: Configure .env for development
        if: github.event.inputs.env == 'development'
        run: |
          echo "API_PREFIX=$API_PREFIX" >> .env
          echo "SIGN_KEY=$SIGN_KEY" >> .env
          echo "CRYPTO_AES_KEY=$CRYPTO_AES_KEY" >> .env
          echo "CRYPTO_AES_IV=$CRYPTO_AES_IV" >> .env
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
        env:
          API_PREFIX: ${{ secrets.DEV_API_PREFIX }}
          SIGN_KEY: ${{ secrets.DEV_SIGN_KEY }}
          CRYPTO_AES_KEY: ${{ secrets.DEV_CRYPTO_AES_KEY }}
          CRYPTO_AES_IV: ${{ secrets.DEV_CRYPTO_AES_IV }}
          SENTRY_DSN: ${{ secrets.DEV_SENTRY_DSN }}

      - name: Configure .env for staging
        if: github.event.inputs.env == 'staging'
        run: |
          echo "API_PREFIX=$API_PREFIX" >> .env
          echo "SIGN_KEY=$SIGN_KEY" >> .env
          echo "CRYPTO_AES_KEY=$CRYPTO_AES_KEY" >> .env
          echo "CRYPTO_AES_IV=$CRYPTO_AES_IV" >> .env
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
        env:
          API_PREFIX: ${{ secrets.STG_API_PREFIX }}
          SIGN_KEY: ${{ secrets.STG_SIGN_KEY }}
          CRYPTO_AES_KEY: ${{ secrets.STG_CRYPTO_AES_KEY }}
          CRYPTO_AES_IV: ${{ secrets.STG_CRYPTO_AES_IV }}
          SENTRY_DSN: ${{ secrets.STG_SENTRY_DSN }}

      - name: Configure .env for production
        if: github.event.inputs.env == 'production'
        run: |
          echo "API_PREFIX=$API_PREFIX" >> .env
          echo "SIGN_KEY=$SIGN_KEY" >> .env
          echo "CRYPTO_AES_KEY=$CRYPTO_AES_KEY" >> .env
          echo "CRYPTO_AES_IV=$CRYPTO_AES_IV" >> .env
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
        env:
          API_PREFIX: ${{ secrets.PROD_API_PREFIX }}
          SIGN_KEY: ${{ secrets.PROD_SIGN_KEY }}
          CRYPTO_AES_KEY: ${{ secrets.PROD_CRYPTO_AES_KEY }}
          CRYPTO_AES_IV: ${{ secrets.PROD_CRYPTO_AES_IV }}
          SENTRY_DSN: ${{ secrets.PROD_SENTRY_DSN }}

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Install Deps
        run: flutter pub get

      - name: Configure Keystore for Android
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      # Build the application.
      - if: github.event.inputs.versionSuffix == 'true'
        run: bash build-android.sh && flutter build appbundle --release --no-tree-shake-icons

      - if: github.event.inputs.versionSuffix != 'true'
        run: flutter build appbundle --release --no-tree-shake-icons

      # Package the build.
      - name: Copy build for Android
        run: cp *.aab $GITHUB_WORKSPACE/
        working-directory: build/app/outputs/bundle/release

      - uses: actions/upload-artifact@v3
        with:
          name: aab-artifact
          path: ./*.aab

  ios-build:
    name: Create ios build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.2'

      - name: Configure .env for development
        if: github.event.inputs.env == 'development'
        run: |
          echo "API_PREFIX=$API_PREFIX" >> .env
          echo "SIGN_KEY=$SIGN_KEY" >> .env
          echo "CRYPTO_AES_KEY=$CRYPTO_AES_KEY" >> .env
          echo "CRYPTO_AES_IV=$CRYPTO_AES_IV" >> .env
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
        env:
          API_PREFIX: ${{ secrets.DEV_API_PREFIX }}
          SIGN_KEY: ${{ secrets.DEV_SIGN_KEY }}
          CRYPTO_AES_KEY: ${{ secrets.DEV_CRYPTO_AES_KEY }}
          CRYPTO_AES_IV: ${{ secrets.DEV_CRYPTO_AES_IV }}
          SENTRY_DSN: ${{ secrets.DEV_SENTRY_DSN }}

      - name: Configure .env for staging
        if: github.event.inputs.env == 'staging'
        run: |
          echo "API_PREFIX=$API_PREFIX" >> .env
          echo "SIGN_KEY=$SIGN_KEY" >> .env
          echo "CRYPTO_AES_KEY=$CRYPTO_AES_KEY" >> .env
          echo "CRYPTO_AES_IV=$CRYPTO_AES_IV" >> .env
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
        env:
          API_PREFIX: ${{ secrets.STG_API_PREFIX }}
          SIGN_KEY: ${{ secrets.STG_SIGN_KEY }}
          CRYPTO_AES_KEY: ${{ secrets.STG_CRYPTO_AES_KEY }}
          CRYPTO_AES_IV: ${{ secrets.STG_CRYPTO_AES_IV }}
          SENTRY_DSN: ${{ secrets.STG_SENTRY_DSN }}

      - name: Configure .env for production
        if: github.event.inputs.env == 'production'
        run: |
          echo "API_PREFIX=$API_PREFIX" >> .env
          echo "SIGN_KEY=$SIGN_KEY" >> .env
          echo "CRYPTO_AES_KEY=$CRYPTO_AES_KEY" >> .env
          echo "CRYPTO_AES_IV=$CRYPTO_AES_IV" >> .env
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
        env:
          API_PREFIX: ${{ secrets.PROD_API_PREFIX }}
          SIGN_KEY: ${{ secrets.PROD_SIGN_KEY }}
          CRYPTO_AES_KEY: ${{ secrets.PROD_CRYPTO_AES_KEY }}
          CRYPTO_AES_IV: ${{ secrets.PROD_CRYPTO_AES_IV }}
          SENTRY_DSN: ${{ secrets.PROD_SENTRY_DSN }}

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Install Deps
        run: flutter pub get

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.P12_BASE64 }}
          BUILD_CERTIFICATE_DEV_BASE64: ${{ secrets.P12_DEV_BASE64 }}
          BUILD_CERT_BASE64: ${{ secrets.CERT_BASE64 }}
          BUILD_CERT_DEV_BASE64: ${{ secrets.CERT_DEV_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
          BUILD_PROVISION_PROFILE_DEV_BASE64: ${{ secrets.PROVISIONING_PROFILE_DEV_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          CERTIFICATE_DEV_PATH=$RUNNER_TEMP/build_certificate_dev.p12
          CERT_PATH=$RUNNER_TEMP/ios_distribution.cer
          CERT_DEV_PATH=$RUNNER_TEMP/development.cer
          PP_PATH=$RUNNER_TEMP/homing_pigeon_appstore.mobileprovision
          PP_DEV_PATH=$RUNNER_TEMP/homing_pigeon_dev.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_CERTIFICATE_DEV_BASE64" | base64 --decode --output $CERTIFICATE_DEV_PATH
          echo -n "$BUILD_CERT_BASE64" | base64 --decode --output $CERT_PATH
          echo -n "$BUILD_CERT_DEV_BASE64" | base64 --decode --output $CERT_DEV_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          echo -n "$BUILD_PROVISION_PROFILE_DEV_BASE64" | base64 --decode --output $PP_DEV_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $CERTIFICATE_DEV_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $CERT_PATH -P "$P12_PASSWORD" -A -t cert -k $KEYCHAIN_PATH
          security import $CERT_DEV_PATH -P "$P12_PASSWORD" -A -t cert -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_DEV_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Build
        if: github.event.inputs.versionSuffix == 'true'
        run: bash build-ios.sh && flutter build ipa --release --export-options-plist=ios/ExportOptions-${{ github.event.inputs.mode }}.plist --dart-define-from-file=ios-pgyer.json

      - name: Build
        if: github.event.inputs.versionSuffix != 'true'
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions-${{ github.event.inputs.mode }}.plist

      # Package the build.
      - name: Copy build for iOS
        run: cp *.ipa $GITHUB_WORKSPACE/
        working-directory: build/ios/ipa

      - uses: actions/upload-artifact@v3
        with:
          name: ios-artifact
          path: ./*.ipa

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/homing_pigeon_appstore.mobileprovision
          rm ~/Library/MobileDevice/Provisioning\ Profiles/homing_pigeon_dev.mobileprovision

